//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int Id { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemName { get; set; }
        public string CateId { get; set; }
        public string CateName { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> DiscountPrice { get; set; }
        public Nullable<int> QuantityDiscount { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> TotalOrder { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
