//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public int Id { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhoneNumber { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerNameAlter { get; set; }
        public string CustomerPhoneNumberAlter { get; set; }
        public string CustomerAddressAlter { get; set; }
        public string SellerId { get; set; }
        public string SellerName { get; set; }
        public string SellerPhoneNumber { get; set; }
        public string SellerAddress { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemName { get; set; }
        public string CateId { get; set; }
        public string CateName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public Nullable<int> DeliverId { get; set; }
        public string DeliverName { get; set; }
        public Nullable<int> DeliveryProcessId { get; set; }
        public Nullable<System.DateTime> OrderedTime { get; set; }
        public Nullable<System.DateTime> AcceptedTime { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<System.DateTime> EndedTime { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
