//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> TotalRating { get; set; }
        public Nullable<int> TotalItem { get; set; }
        public Nullable<int> Address { get; set; }
        public string Description { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
